# Rustfmt makes too many mistakes to be applied unconditionally to the whole code.
# Please don't apply rustfmt to code in this project. Disable rustfmt in your editor.
disable_all_formatting = true
max_width = 160
binop_separator = "Back"
imports_granularity = "Module"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 100
struct_lit_width = 30
struct_variant_width = 50
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
chain_width = 90
comment_width = 200
condense_wildcard_suffixes = true
edition = "2021"
empty_item_single_line = false
fn_params_layout = "Compressed"
fn_call_width = 100
fn_single_line = false
imports_layout = "Horizontal"
match_block_trailing_comma = true
